[2022-09-25 17:44:10,727][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-09-25 17:44:10,754][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-09-25 17:44:10,754][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2022-09-25 17:44:10,762][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2022-09-25 17:44:10,970][__main__][INFO] - Instantiating datamodule <src.datamodules.cifar10_datamodule.CIFAR10DataModule>
[2022-09-25 17:44:10,996][__main__][INFO] - Instantiating model <src.models.cifar10_module.CIFAR10LitModule>
[2022-09-25 17:44:11,664][timm.models.helpers][INFO] - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
[2022-09-25 17:44:11,915][__main__][INFO] - Instantiating loggers...
[2022-09-25 17:44:11,928][src.utils.utils][WARNING] - Logger config is empty.
[2022-09-25 17:44:11,928][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-09-25 17:44:12,074][__main__][INFO] - Starting testing!
[2022-09-25 17:44:15,518][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "C:\Users\katta\Desktop\MLOPS\Week3\cifar10\src\utils\utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\katta\Desktop\MLOPS\Week3\cifar10\src\eval.py", line 86, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 864, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 911, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1065, in _restore_modules_and_callbacks
    self._checkpoint_connector.resume_start(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 85, in resume_start
    self._loaded_checkpoint = self._load_and_validate_checkpoint(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 89, in _load_and_validate_checkpoint
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 339, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\plugins\io\torch_plugin.py", line 83, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint at {path} not found. Aborting training.")
FileNotFoundError: Checkpoint at Week3\cifar10\logs\train\multiruns\2022-09-25_11-06-56\19\checkpoints\epoch_009.ckpt not found. Aborting training.
[2022-09-25 17:44:15,534][src.utils.utils][INFO] - Closing loggers...
[2022-09-25 17:45:35,792][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-09-25 17:45:35,808][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-09-25 17:45:35,808][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2022-09-25 17:45:35,808][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2022-09-25 17:45:36,025][__main__][INFO] - Instantiating datamodule <src.datamodules.cifar10_datamodule.CIFAR10DataModule>
[2022-09-25 17:45:36,033][__main__][INFO] - Instantiating model <src.models.cifar10_module.CIFAR10LitModule>
[2022-09-25 17:45:36,526][timm.models.helpers][INFO] - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
[2022-09-25 17:45:36,735][__main__][INFO] - Instantiating loggers...
[2022-09-25 17:45:36,738][src.utils.utils][WARNING] - Logger config is empty.
[2022-09-25 17:45:36,738][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-09-25 17:45:36,887][__main__][INFO] - Starting testing!
[2022-09-25 17:45:40,362][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "C:\Users\katta\Desktop\MLOPS\Week3\cifar10\src\utils\utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\katta\Desktop\MLOPS\Week3\cifar10\src\eval.py", line 86, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 864, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 911, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1065, in _restore_modules_and_callbacks
    self._checkpoint_connector.resume_start(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 85, in resume_start
    self._loaded_checkpoint = self._load_and_validate_checkpoint(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 89, in _load_and_validate_checkpoint
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 339, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "C:\Users\katta\anaconda3\envs\mlopsw2\lib\site-packages\pytorch_lightning\plugins\io\torch_plugin.py", line 83, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint at {path} not found. Aborting training.")
FileNotFoundError: Checkpoint at Week3\cifar10\logs\train\multiruns\2022-09-25_11-06-56\19\checkpoints\epoch_009.ckpt not found. Aborting training.
[2022-09-25 17:45:40,380][src.utils.utils][INFO] - Closing loggers...
[2022-09-25 17:46:02,572][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-09-25 17:46:02,601][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-09-25 17:46:02,609][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2022-09-25 17:46:02,609][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2022-09-25 17:46:02,825][__main__][INFO] - Instantiating datamodule <src.datamodules.cifar10_datamodule.CIFAR10DataModule>
[2022-09-25 17:46:02,833][__main__][INFO] - Instantiating model <src.models.cifar10_module.CIFAR10LitModule>
[2022-09-25 17:46:03,275][timm.models.helpers][INFO] - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
[2022-09-25 17:46:03,478][__main__][INFO] - Instantiating loggers...
[2022-09-25 17:46:03,490][src.utils.utils][WARNING] - Logger config is empty.
[2022-09-25 17:46:03,490][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-09-25 17:46:03,638][__main__][INFO] - Starting testing!
[2022-09-25 17:46:18,783][src.utils.utils][INFO] - Closing loggers...
[2022-09-25 17:46:18,796][src.utils.utils][INFO] - Output dir: C:\Users\katta\Desktop\MLOPS\Week3\cifar10\logs\eval\runs\2022-09-25_17-46-02
